### ISSUE TITLE
Problem: Review sampledata

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica-sampledata#32]
It's been a while since the sampledata set was thoroughly reviewed. Many things have been added over time, and it's likely that there's unnecessary repetition within the sample data. At the same time, the feature set in Archivematica has been growing quickly, so there are features for which there is no sample data (see, for example, #31). Even some basic features are not testable with the current sample data (see #28).

We should consider how the auto-generated sample data fits in, and if it needs to be incorporated in a better/more readily apparent way - not sure how to do this, but it warrants consideration.

We could also look at how the sampledata set is deployed to sandbox and testing servers.

Finally, better documentation about the data and what the various transfers are supposed to test would be helpful (probably as part of the README here).

**Comment by ross-spencer** [comment]
RE: #31, we did have some MKV (see the issue) but I feel that maybe  it wasn't as intuitive as it could be to find them. Probably a point to consider when we reorganise this.

**Comment by ross-spencer** [comment]
Looking for `.zip` files this morning I can see some examples where expanding the `README.md` would help to provide context and set expectations. https://github.com/artefactual/archivematica-sampledata/blob/master/TestTransfers/1000.zip We can have `README.md` at different sublevels as well, but a trade-off would be that file ending up in Transfers when we might want to test something minus that.

**Comment by ross-spencer** [comment]
One thing we might want to consider is how we might want to incorporate sample data that deliberately breaks Archivematica - it could range from some of the ones we have already - 'checksums are wrong', or it could be sample data, like deliberately [fuzzed](https://github.com/secfigo/Awesome-Fuzzing#file-format-fuzzers) format samples. But one benefit I can see is it can help us to develop finer grained control over Archivematica's exception behaviour. The type of thing @joel-simpson has been looking at for example. It might just make it easier to point folk at 'good transfers' during camps too.

**Comment by ross-spencer** [comment]
Another point to consider will be naming conventions for folders and files. This might be more difficult to correct in the short term where tests rely on specific filenames, but it will make the repository look better in time. An example of the inconsistency:
```
ross-spencer@artefactual:~/git/artefactual/archivematica-sampledata/TestTransfers:$ ls
'10,000 files 10,000 directories.tar.7z'   bagitTests                 hiddenFile                 NoExtensionsImages                   Unicode
'1000 directories.tar.7z'                  bulkextractorTests         mac-Icon                   NoNormalizationPathsNoExtensions     virusTests
 1000.zip                                  emptyDirectory             Maildir                    passwordProtected                    zippedWithBadNames
'950 directories.tar.7z'                  "Evelyn's photos"           manualNormalization        small
 acceptance-tests                         'extract 0 byte file.txt'   ManualNormalization        submissionDocNormalizationWillFail
 badNames                                  fixityCheckShouldFail     'more compression.tar.7z'   thumbs_db_file
```

**Comment by ross-spencer** [comment]
From Slack today two additional points cropped up.

* Additional sub-modules we could link to: https://github.com/IISH/archivematica-test-collections/
* But also, creating a useful distinction between development sample data and sample data useful for testing Archivematica. The distinction between the two I think is in the spirit of the original proposal from Sara. Just making it clearer here.

**Comment by ross-spencer** [comment]
Related to https://github.com/archivematica/Issues/issues/859 
Replaced by https://github.com/archivematica/Issues/issues/859

**Comment by sallain** [comment]
@ross-spencer :woman_facepalming: I only thought to look for an issue in the Issues repo!

**Comment by ross-spencer** [comment]
@sallain on the plus side we're one issue down, two to go here! (Also I only happened to be in here this morning, but can't remember what I was looking for...)
