### ISSUE TITLE
Problem: Need a file over 20mb with a virus for testing

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica-sampledata#8]
There are 4 scenarios to effectively test clamAV:

1) files < 20M that have virus  WE HAVE
2) files < 20M that don’t have virus WE HAVE
3) files > 20 M that have virus WE DO NOT HAVE
4) files > 20M that don’t have virus WE HAVE

We need a file that is over 20mb that has a virus.

**Comment by ross-spencer** [comment]
Hi Kelly, 

I have written the following code that should allow us to make a file of any size containing a virus. I have generated a handful of binaries. I'm hoping one of the two Darwin ones will work on your Mac setup.

https://github.com/ross-spencer/badfood/releases/tag/v0.0.2-nukem

For example, for a 100MB sample file:

		ross-spencer@artefactual:$ ./badfood -size 100 -nukem
		Outputting samplefile
		ross-spencer@artefactual:$ clamscan --max-scansize=200M --max-filesize=200M samplefile 
		samplefile: Win.Trojan.Nukem-1 FOUND

		----------- SCAN SUMMARY -----------
		Known viruses: 6333383
		Engine version: 0.99.2
		Scanned directories: 0
		Scanned files: 1
		Infected files: 1
		Data scanned: 50.50 MB
		Data read: 100.00 MB (ratio 0.51:1)
		Time: 55.288 sec (0 m 55 s)

		--

		#/etc/clamav/clamd.conf settings...
		MaxScanSize 200M
		MaxFileSize 200M

		--

		ross-spencer@artefactual:$ clamdscan samplefile 
		/home/ross-spencer/git/go/src/github.com/ross-spencer/badfood/samplefile: Win.Trojan.Nukem-1 FOUND

		----------- SCAN SUMMARY -----------
		Infected files: 1
		Time: 22.354 sec (0 m 22 s)

You'll see in the output that Clamscan and Clamdscan are a little pedantic. I set the upper limits to 200M(B) not 100. This might be useful to keep in mind when testing. 

The Nukem flag is in relation to a '98 virus that clamscan and clamdscan can identify. This is important as the virus is described by ClamAV as being able to appear anywhere in the file. (Compared to the EICAR test virus I describe the potential limitations of here: https://github.com/ross-spencer/badfood#the-problem-with-eicar) 

The original 0.0.1 release earlier today focuses on a virus that we describe for ourselves and has no relation to any existing virus, but can also 'exist' anywhere in the file. There may be benefits to using this test file/binary over others in the future.

Can chat more over Slack. One thing I'd like to ask is how to address creating the feature file referenced here: https://github.com/artefactual-labs/archivematica-acceptance-tests/issues/36

**Comment by ross-spencer** [comment]
Okay, so following today's meeting I've made two sample files available ~30MB each to test this. Will shoot them over to Santi. Tested standalone and we see the following correct output:

		ross-spencer@artefactual:$ clamdscan test-files/*.dat
		/home/ross-spencer/git/go/src/github.com/ross-spencer/badfood/test-files/eicar-test-file.dat: Eicar-Test-Signature FOUND
		/home/ross-spencer/git/go/src/github.com/ross-spencer/badfood/test-files/nukem-test-file.dat: Win.Trojan.Nukem-1 FOUND

		----------- SCAN SUMMARY -----------
		Infected files: 2
		Time: 6.647 sec (0 m 6 s)
		ross-spencer@artefactual:$ clamscan --max-scansize=32M --max-filesize=32M test-files/*.dat
		test-files/eicar-test-file.dat: Eicar-Test-Signature FOUND
		test-files/nukem-test-file.dat: Win.Trojan.Nukem-1 FOUND

		----------- SCAN SUMMARY -----------
		Known viruses: 6334631
		Engine version: 0.99.2
		Scanned directories: 0
		Scanned files: 2
		Infected files: 2
		Data scanned: 15.38 MB
		Data read: 60.00 MB (ratio 0.26:1)
		Time: 31.647 sec (0 m 31 s)

**Comment by kellyannewithane** [comment]
Hey Ross,

Just realized virus scan didn't actually work.

duh


Regards,

Kelly Stewart

Systems Archivist
Artefactual Systems <https://www.artefactual.com/>
604-527-2056 <(604)%20527-2056>
